version: '3.4'

services:
  flaskdevop:
    restart: always
    image: page-tracker
    build:
      context: ./tracker/
      dockerfile: Dockerfile
    # command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5002"]
    ports:
      - 5000:5000
      - 5678:5678
    environment:
      - FLASK_APP=/page_tracker/app.py
      - REDIS_URL=redis://redis:6379 
  notification-service:
    restart: always
    depends_on: 
      - flaskdevop
    image: notification-service
    build:
      context: ./notification
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  redis:
    image: redis:alpine
    container_name: tracker
